### ISSUE TITLE
 transport is not a constructor error

### ISSUE THREAD

**Issue by anildigital** [loggly/winston-loggly-bulk#22]
```exited with code 1
terminated by SIGTERM
 TypeError: transport is not a constructor
     at Logger.add (project/appNode/node_modules/winston/lib/winston/logger.js:481:41)
     at Object.winston.(anonymous function) [as add] (project/appNode/node_modules/winston/lib/winston.js:86:34)
     at Object.<anonymous> (project/appNode/app/logger.coffee:5:9)
     at Object.<anonymous> (project/appNode/app/logger.coffee:1:1)
     at Module._compile (module.js:570:32)
     at Object.loadFile (project/appNode/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
     at Module.load (project/appNode/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
     at tryModuleLoad (module.js:446:12)
     at Function.Module._load (module.js:438:3)
     at Module.require (module.js:497:17)
     at require (internal/module.js:20:19)
```

Using winston like 

```winston = require 'winston'
require 'winston-loggly-bulk'
LOGGLY_KEY = process.env.LOGGLY_KEY

winston.add winston.transports.Loggly,
token: LOGGLY_KEY
subdomain: process.env.LOGGLY_SUBDOMAIN  || "myapp"
tags: ["myapp-node", process.env.CONTEXT]
json:true```

I am using Node version `v6.11.1`

**Comment by mostlyjason** [comment]
@Shwetajain148 is this related to #19?

**Comment by anildigital** [comment]
It's fixed. Looks like node version and node_modules mismatch issue.

**Comment by mostlyjason** [comment]
Ok closing this then
